### PR TITLE
add collar_line_odom node

### PR DESCRIPTION
**Pull request by ompugao**
which depends on https://github.com/robofit/but_velodyne_lib

### CODE REVIEW

**Comment by martin-velas** [comment]
I have tried to build the package but this errors occurred: http://pastebin.com/YJ3YXQ4E - can you fix it, please?

I would also prefer if you move the code into separated package ```but_velodyne_odom``` (instead of putting into the existing package ```but_velodyne_proc```) - would it be possible?

One last thing - would it be possible to include some simple test/demo? Smth linke [demo.sh](https://github.com/robofit/but_velodyne_lib/blob/master/scripts/demo.sh) - in form of launch file, bash script or whatever you will find reasonable ... 

Thanks!

**Comment by ompugao** [comment]
> I have tried to build the package but this errors occurred: http://pastebin.com/YJ3YXQ4E - can you fix it, please?
please merge https://github.com/robofit/but_velodyne_lib/pull/9

**Comment by martin-velas** [comment]
yes - that helped! :)

**Comment by ompugao** [comment]
updated

**Comment by martin-velas** [comment]
Hi - thanks for update!

First of all - some formal notes: please, squash the commits into the single one (also the future commits). Also do not add `pose.graph` file into the repo. Thanks.

I have tried to run the launchfile like this:
`roslaunch but_velodyne_odom collar_line_odometry.launch`
and then (after the nodelet has been initialized) feed it with data:
`for f in 00000*.pcd; do rosrun pcl_ros pcd_to_pointcloud $f /cloud_pcd:=/velodyne_points; sleep 1; done`
but it failed with following output: http://pastebin.com/wZdWKMXv. You can download the PCD files from https://www.fit.vutbr.cz/~ivelas/files/kitti-sample/00000$x.pcd where x={0,1,2,3,4}.

Can you, please, take look at it? Am I doing smth wrong? Thanks!

**Comment by martin-velas** [comment]
FYI - I'm also attaching all available log files [logs.zip](https://github.com/robofit/but_velodyne/files/187698/logs.zip) (file manager-1.log mentioned in error output above does not actually exist)

**Comment by ompugao** [comment]
> First of all - some formal notes: please, squash the commits into the single one (also the future commits). Also do not add pose.graph file into the repo. Thanks.

Done.

>I have tried to run the launchfile like this:
roslaunch but_velodyne_odom collar_line_odometry.launch
and then (after the nodelet has been initialized) feed it with data:
for f in 00000*.pcd; do rosrun pcl_ros pcd_to_pointcloud $f /cloud_pcd:=/velodyne_points; sleep 1; done
but it failed with following output: http://pastebin.com/wZdWKMXv. You can download the PCD files from https://www.fit.vutbr.cz/~ivelas/files/kitti-sample/00000$x.pcd where x={0,1,2,3,4}.

it works on my machine. I cannot reproduce it.
it seems that rosmaster gets messed up somehow.
please attach gdb to nodelet manager and see what's going on on your end. 

```
<launch>
    <node pkg="nodelet" type="nodelet" name="manager" args="manager" output="screen"
        launch-prefix="xterm -fn 12x24 -e gdb --args "
        />
    <node pkg="nodelet" type="nodelet" name="collar_line_odom_node" args="load but_velodyne_odom/CollarLineOdomNodelet manager">
        <remap from="~input/cloud" to="/velodyne_points"/>
        <remap from="~output/odom" to="/velodyen_odom"/>
        <param name="save_file" value="false"/>
    </node>
</launch>
```

thanks.

**Comment by martin-velas** [comment]
I just recompiled the library and the wrapper from scratch and everything starts to work fine ... like a charm ...

Anyway - thanks a lot for contribution and the updates of PR.

**Comment by ompugao** [comment]
;)

**Pull request merged**
